// packages/angular/src/lib/timeline-controls.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  ElementRef,
  ViewChild,
  AfterViewInit,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  HostListener,
} from '@angular/core';
import * as Cesium from 'cesium';
import {
  type TimelineTheme,
  type TimelineLabels,
  DEFAULT_LABELS,
  resolveLabel,
  formatDateTime,
  getTimezoneAbbr,
  splitForDisplay,
} from '@kteneyck/cesium-timeline-core';

@Component({
  selector: 'ct-timeline-controls',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      #container
      [style.display]="isNarrow ? 'flex' : 'grid'"
      [style.grid-template-columns]="isNarrow ? undefined : '1fr auto 1fr'"
      [style.align-items]="'center'"
      [style.padding]="'6px 16px'"
      [style.background-color]="theme.controlBarBackground"
      [style.border-bottom]="'1px solid ' + theme.controlBarBorder"
      [style.font-family]="'system-ui, -apple-system, sans-serif'"
    >
      <!-- Left: Datetime + LIVE (if position=left) -->
      <div style="display:flex;align-items:center;gap:8px;flex-shrink:0">
        <div
          (click)="!live && dateTimeClick.emit()"
          [title]="(!live && dateTimeClick.observed) ? l.dateTimeClickTooltip : ''"
          [style.color]="theme.labelColor"
          style="font-family:monospace;line-height:1.15;border-radius:4px;padding:2px 4px;transition:background 0.15s"
          [style.cursor]="(!live && dateTimeClick.observed) ? 'pointer' : 'default'"
        >
          @if (timeFormat) {
            <div style="font-size:2em;font-weight:bold;letter-spacing:0.02em">
              {{ formattedTime }}
            </div>
          }
          @if (dateFormat) {
            <div style="display:flex;align-items:center;gap:6px">
              <span [style.color]="theme.buttonActiveColor" style="font-size:1.15em;letter-spacing:0.03em">
                {{ formattedDate }}
              </span>
              @if (timezoneAbbr) {
                <span
                  [style.color]="theme.labelColor"
                  style="font-size:1.04em;font-weight:bold;letter-spacing:0.04em;opacity:0.7"
                >{{ timezoneAbbr }}</span>
              }
            </div>
          }
        </div>

        @if (liveButtonPosition === 'left' && (showLive || (!isNormalSpeed && !live))) {
          <div style="display:flex;align-items:center;gap:4px">
            @if (showLive) {
              <button
                (click)="!live && jumpToLive.emit()"
                [style.color]="(live || isLive) ? theme.controlBarBackground : theme.buttonActiveColor"
                [style.background-color]="(live || isLive) ? theme.buttonActiveColor : 'transparent'"
                [style.border-color]="theme.buttonActiveColor"
                [style.opacity]="1"
                [style.width.px]="liveSize.width"
                [style.min-width.px]="liveSize.width"
                [style.height.px]="liveSize.height"
                [style.font-size]="liveSize.fontSize"
                [style.border-radius]="liveSize.borderRadius"
                [style.cursor]="live ? 'default' : 'pointer'"
                style="background:none;border:1px solid;font-weight:bold;letter-spacing:0.05em;display:flex;align-items:center;justify-content:center;padding:0;gap:4px;font-family:system-ui,-apple-system,sans-serif;transition:opacity 0.15s"
                [title]="(live || isLive) ? l.liveActiveTooltip : l.liveTooltip"
              >
                @if (live || isLive) {
                  <span
                    [style.width.px]="liveSize.dot"
                    [style.height.px]="liveSize.dot"
                    [style.background-color]="theme.liveDotColor"
                    style="border-radius:50%;display:inline-block;flex-shrink:0"
                  ></span>
                }
                {{ (live || isLive) ? l.liveActiveLabel : l.liveLabel }}
              </button>
            }
            @if (!isNormalSpeed && !live) {
              <button
                data-speed-badge
                (click)="toggleSpeedOverlay()"
                [style.color]="theme.buttonActiveColor"
                [style.border-color]="theme.buttonActiveColor + '44'"
                [style.min-width.px]="liveSize.width"
                [style.height.px]="liveSize.height"
                style="background:none;border:1px solid;cursor:pointer;font-size:11px;border-radius:4px;display:flex;align-items:center;justify-content:center;width:auto;padding:0 8px;font-family:system-ui,-apple-system,sans-serif;transition:background-color 0.15s"
                [title]="l.resetSpeedTooltip"
              >{{ isRewinding ? '◀ ' + absMultiplier + '×' : absMultiplier + '× ▶' }}</button>
              @if (speedOverlayOpen && speedOverlayPos) {
                <div
                  data-speed-overlay
                  [style.background-color]="theme.controlBarBackground"
                  [style.border]="'1px solid ' + theme.controlBarBorder"
                  [style.color]="theme.labelColor"
                  [style.bottom.px]="speedOverlayPos.bottom"
                  [style.left.px]="speedOverlayPos.left"
                  style="position:fixed;z-index:2147483647;display:flex;flex-direction:column;gap:8px;padding:10px 12px;border-radius:6px;box-shadow:0 4px 16px rgba(0,0,0,0.3);min-width:170px;font-family:system-ui,-apple-system,sans-serif"
                >
                  <div style="font-size:11px;font-weight:bold;letter-spacing:0.03em">{{ l.speedOverlayTitle }}</div>
                  <div style="display:flex;align-items:center;gap:8px">
                    <input
                      type="range"
                      [attr.min]="minSpeed"
                      [attr.max]="maxSpeed"
                      step="1"
                      [value]="absMultiplier"
                      (input)="onSliderChange($event)"
                      [attr.aria-label]="l.speedInputLabel"
                      [style.accent-color]="theme.buttonActiveColor"
                      style="flex:1"
                    />
                    <input
                      type="number"
                      class="ct-speed-input"
                      [attr.min]="minSpeed"
                      [attr.max]="maxSpeed"
                      [value]="speedInputValue"
                      (input)="onSpeedInputChange($event)"
                      (blur)="commitSpeedInput()"
                      (keydown.enter)="commitSpeedInput()"
                      [attr.aria-label]="l.speedInputLabel"
                      [style.border]="'1px solid ' + theme.controlBarBorder"
                      [style.color]="theme.labelColor"
                      style="width:48px;font-size:12px;padding:2px 4px;border-radius:4px;background:transparent;font-family:inherit"
                    />
                  </div>
                  <button
                    (click)="resetSpeed.emit(); closeSpeedOverlay()"
                    [style.color]="theme.buttonActiveColor"
                    [style.border-color]="theme.buttonActiveColor + '44'"
                    [style.height.px]="liveSize.height"
                    style="align-self:flex-start;background:none;border:1px solid;cursor:pointer;font-size:11px;border-radius:4px;padding:0 10px;font-family:inherit"
                    [title]="l.resetSpeedTitle"
                  >{{ l.resetSpeedLabel }}</button>
                </div>
              }
            }
          </div>
        }
      </div>

      <!-- Center: Transport buttons -->
      <div
        style="display:flex;align-items:center;gap:2px"
        [style.flex]="isNarrow ? '1' : undefined"
        [style.justify-content]="isNarrow ? 'center' : undefined"
      >
        @if (!live && showJumpToStart !== false) {
          <button
            (click)="hasStartTime && jumpToStart.emit()"
            [disabled]="!hasStartTime"
            [style.color]="theme.buttonColor"
            [style.opacity]="hasStartTime ? 1 : 0.3"
            [style.cursor]="hasStartTime ? 'pointer' : 'default'"
            class="ct-btn"
            [title]="hasStartTime ? l.jumpToStartTooltip : l.noStartTimeTooltip"
          >⏮</button>
        }

        @if (!live) {
          <button
            (click)="rewind.emit()"
            [style.color]="isRewinding ? theme.buttonActiveColor : theme.buttonColor"
            [style.border-color]="isRewinding ? theme.buttonActiveColor + '33' : 'transparent'"
            class="ct-btn"
            [title]="isRewinding ? resolveRewindActive(absMultiplier) : l.rewindTooltip"
          >◀◀</button>
        }

        @if (!live) {
          <button
            (click)="playPause.emit(!isPlaying)"
            [style.color]="theme.buttonActiveColor"
            [style.border-color]="theme.buttonActiveColor + '55'"
            [style.padding-left]="isPlaying ? '0' : '2px'"
            class="ct-btn ct-btn-play"
            [title]="isPlaying ? l.pauseTooltip : (isRewinding ? l.playFromRewindTooltip : l.playTooltip)"
          >
            @if (isPlaying) {
              <svg width="14" height="16" viewBox="0 0 14 16" fill="currentColor">
                <rect x="1" y="0" width="4" height="16" rx="1"/>
                <rect x="9" y="0" width="4" height="16" rx="1"/>
              </svg>
            } @else {
              ▶
            }
          </button>
        }

        @if (!live) {
          <button
            (click)="fastForward.emit()"
            [style.color]="isFastForward ? theme.buttonActiveColor : theme.buttonColor"
            [style.border-color]="isFastForward ? theme.buttonActiveColor + '33' : 'transparent'"
            class="ct-btn ct-btn-wide"
            [title]="isFastForward ? resolveFastForwardActive(absMultiplier) : l.fastForwardTooltip"
          >▶▶</button>
        }

        @if (!live && showJumpToEnd !== false) {
          <button
            (click)="hasEndTime && jumpToEnd.emit()"
            [disabled]="!hasEndTime"
            [style.color]="theme.buttonColor"
            [style.opacity]="hasEndTime ? 1 : 0.3"
            [style.cursor]="hasEndTime ? 'pointer' : 'default'"
            class="ct-btn"
            [title]="hasEndTime ? l.jumpToEndTooltip : l.noEndTimeTooltip"
          >⏭</button>
        }
      </div>

      <!-- Right: LIVE (if position=right) + swim-lane toggle -->
      @if (!isNarrow) {
        <div style="display:flex;justify-content:flex-end;align-items:center;gap:8px">
          @if (liveButtonPosition === 'right' && (showLive || (!isNormalSpeed && !live))) {
            <div style="display:flex;align-items:center;gap:4px">
              @if (showLive) {
                <button
                  (click)="!live && jumpToLive.emit()"
                  [style.color]="(live || isLive) ? theme.controlBarBackground : theme.buttonActiveColor"
                  [style.background-color]="(live || isLive) ? theme.buttonActiveColor : 'transparent'"
                  [style.border-color]="theme.buttonActiveColor"
                  [style.opacity]="1"
                  [style.width.px]="liveSize.width"
                  [style.min-width.px]="liveSize.width"
                  [style.height.px]="liveSize.height"
                  [style.font-size]="liveSize.fontSize"
                  [style.border-radius]="liveSize.borderRadius"
                  [style.cursor]="live ? 'default' : 'pointer'"
                  style="background:none;border:1px solid;font-weight:bold;letter-spacing:0.05em;display:flex;align-items:center;justify-content:center;padding:0;gap:4px;font-family:system-ui,-apple-system,sans-serif;transition:opacity 0.15s"
                  [title]="(live || isLive) ? l.liveActiveTooltip : l.liveTooltip"
                >
                  @if (live || isLive) {
                    <span
                      [style.width.px]="liveSize.dot"
                      [style.height.px]="liveSize.dot"
                      [style.background-color]="theme.liveDotColor"
                      style="border-radius:50%;display:inline-block;flex-shrink:0"
                    ></span>
                  }
                  {{ (live || isLive) ? l.liveActiveLabel : l.liveLabel }}
                </button>
              }
              @if (!isNormalSpeed && !live) {
                <button
                  data-speed-badge
                  (click)="toggleSpeedOverlay()"
                  [style.color]="theme.buttonActiveColor"
                  [style.border-color]="theme.buttonActiveColor + '44'"
                  [style.min-width.px]="liveSize.width"
                  [style.height.px]="liveSize.height"
                  style="background:none;border:1px solid;cursor:pointer;font-size:11px;border-radius:4px;display:flex;align-items:center;justify-content:center;width:auto;padding:0 8px;font-family:system-ui,-apple-system,sans-serif;transition:background-color 0.15s"
                  [title]="l.resetSpeedTooltip"
                >{{ isRewinding ? '◀ ' + absMultiplier + '×' : absMultiplier + '× ▶' }}</button>
                @if (speedOverlayOpen && speedOverlayPos) {
                  <div
                    data-speed-overlay
                    [style.background-color]="theme.controlBarBackground"
                    [style.border]="'1px solid ' + theme.controlBarBorder"
                    [style.color]="theme.labelColor"
                    [style.bottom.px]="speedOverlayPos.bottom"
                    [style.right.px]="speedOverlayPos.right"
                    style="position:fixed;z-index:2147483647;display:flex;flex-direction:column;gap:8px;padding:10px 12px;border-radius:6px;box-shadow:0 4px 16px rgba(0,0,0,0.3);min-width:170px;font-family:system-ui,-apple-system,sans-serif"
                  >
                    <div style="font-size:11px;font-weight:bold;letter-spacing:0.03em">{{ l.speedOverlayTitle }}</div>
                    <div style="display:flex;align-items:center;gap:8px">
                      <input
                        type="range"
                        [attr.min]="minSpeed"
                        [attr.max]="maxSpeed"
                        step="1"
                        [value]="absMultiplier"
                        (input)="onSliderChange($event)"
                        [attr.aria-label]="l.speedInputLabel"
                        [style.accent-color]="theme.buttonActiveColor"
                        style="flex:1"
                      />
                      <input
                        type="number"
                        class="ct-speed-input"
                        [attr.min]="minSpeed"
                        [attr.max]="maxSpeed"
                        [value]="speedInputValue"
                        (input)="onSpeedInputChange($event)"
                        (blur)="commitSpeedInput()"
                        (keydown.enter)="commitSpeedInput()"
                        [attr.aria-label]="l.speedInputLabel"
                        [style.border]="'1px solid ' + theme.controlBarBorder"
                        [style.color]="theme.labelColor"
                        style="width:48px;font-size:12px;padding:2px 4px;border-radius:4px;background:transparent;font-family:inherit"
                      />
                    </div>
                    <button
                      (click)="resetSpeed.emit(); closeSpeedOverlay()"
                      [style.color]="theme.buttonActiveColor"
                      [style.border-color]="theme.buttonActiveColor + '44'"
                      [style.height.px]="liveSize.height"
                      style="align-self:flex-start;background:none;border:1px solid;cursor:pointer;font-size:11px;border-radius:4px;padding:0 10px;font-family:inherit"
                      [title]="l.resetSpeedTitle"
                    >{{ l.resetSpeedLabel }}</button>
                  </div>
                }
              }
            </div>
          }
          @if (hasSwimLaneToggle) {
            <button
              (click)="toggleSwimLanes.emit()"
              [style.color]="theme.buttonActiveColor"
              [style.border-color]="theme.buttonActiveColor + '33'"
              class="ct-btn"
              [title]="swimLanesVisible ? l.collapseSwimLanesTooltip : l.expandSwimLanesTooltip"
            >
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                @if (swimLanesVisible) {
                  <polyline points="3,5 7,9 11,5"/>
                } @else {
                  <polyline points="3,9 7,5 11,9"/>
                }
              </svg>
            </button>
          }
        </div>
      }

      @if (isNarrow && hasSwimLaneToggle) {
        <button
          (click)="toggleSwimLanes.emit()"
          [style.color]="theme.buttonActiveColor"
          [style.border-color]="theme.buttonActiveColor + '33'"
          class="ct-btn"
          style="margin-left:4px"
          [title]="swimLanesVisible ? l.collapseSwimLanesTooltip : l.expandSwimLanesTooltip"
        >
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            @if (swimLanesVisible) {
              <polyline points="3,5 7,9 11,5"/>
            } @else {
              <polyline points="3,9 7,5 11,9"/>
            }
          </svg>
        </button>
      }
    </div>
  `,
  styles: [`
    :host { display: block; }
    .ct-btn {
      background: none;
      border: 1px solid transparent;
      cursor: pointer;
      font-size: 16px;
      padding: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      min-width: 32px;
      width: 32px;
      height: 32px;
      border-radius: 4px;
      transition: background-color 0.15s, color 0.15s;
      font-family: system-ui, -apple-system, sans-serif;
      flex-shrink: 0;
      line-height: 1;
    }
    .ct-btn:hover { background-color: rgba(255,255,255,0.1); }
    .ct-btn-wide {
      width: auto;
      padding: 0 6px;
    }
    .ct-btn-play {
      font-size: 18px;
      width: 40px;
      min-width: 40px;
      height: 40px;
      border-radius: 50%;
    }
    .ct-speed-input::-webkit-outer-spin-button,
    .ct-speed-input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }
    .ct-speed-input {
      -moz-appearance: textfield;
    }
  `],
})
export class TimelineControlsComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() currentTime!: Cesium.JulianDate;
  @Input() isPlaying = false;
  @Input() multiplier = 1;
  @Input() dateTimeFormat?: string;
  @Input() timezone?: string;
  @Input() isLive = false;
  @Input() hasStartTime = false;
  @Input() hasEndTime = false;
  @Input() showJumpToStart?: boolean;
  @Input() showJumpToEnd?: boolean;
  @Input() theme!: TimelineTheme;
  @Input() swimLanesVisible?: boolean;
  @Input() labels?: Partial<TimelineLabels>;
  @Input() liveButtonSize: 'sm' | 'md' | 'lg' = 'md';
  @Input() liveButtonPosition: 'left' | 'right' = 'left';
  /** @see TimelineBaseProps.showLive */
  @Input() showLive = true;
  /** @see TimelineBaseProps.live */
  @Input() live = false;
  /** @see TimelineBaseProps.minSpeed */
  @Input() minSpeed = 1;
  /** @see TimelineBaseProps.maxSpeed */
  @Input() maxSpeed = 100;

  @Output() dateTimeClick = new EventEmitter<void>();
  @Output() playPause = new EventEmitter<boolean>();
  @Output() jumpToStart = new EventEmitter<void>();
  @Output() rewind = new EventEmitter<void>();
  @Output() fastForward = new EventEmitter<void>();
  @Output() jumpToEnd = new EventEmitter<void>();
  @Output() jumpToLive = new EventEmitter<void>();
  @Output() resetSpeed = new EventEmitter<void>();
  @Output() setSpeed = new EventEmitter<number>();
  @Output() toggleSwimLanes = new EventEmitter<void>();

  constructor(private cdr: ChangeDetectorRef, private elRef: ElementRef<HTMLElement>) {}

  @ViewChild('container') containerRef!: ElementRef<HTMLDivElement>;

  isNarrow = false;
  private ro?: ResizeObserver;

  // ── Playback-speed overlay (slider + input, opened from the speed badge) ──
  speedOverlayOpen = false;
  speedInputValue = '1';
  /** Fixed-position coordinates (viewport-relative) so the overlay escapes any
   *  ancestor's `overflow: hidden` and stacks above other page content (e.g. a
   *  Cesium globe elsewhere on the page). Recomputed on open/resize/scroll. */
  speedOverlayPos: { bottom: number; left?: number; right?: number } | null = null;
  private overlayResizeListener?: () => void;
  private overlayScrollListener?: () => void;

  get isRewinding(): boolean { return this.multiplier < 0; }
  get isFastForward(): boolean { return this.multiplier > 1; }
  get isNormalSpeed(): boolean { return this.multiplier === 1; }
  get absMultiplier(): number { return Math.abs(this.multiplier); }
  get hasSwimLaneToggle(): boolean { return this.swimLanesVisible != null; }

  private static readonly LIVE_SIZE_MAP = {
    sm: { width: 44, height: 18, fontSize: '10px', dot: 5, borderRadius: '3px' },
    md: { width: 56, height: 22, fontSize: '11px', dot: 6, borderRadius: '3px' },
    lg: { width: 72, height: 30, fontSize: '13px', dot: 8, borderRadius: '4px' },
  } as const;

  get liveSize() { return TimelineControlsComponent.LIVE_SIZE_MAP[this.liveButtonSize]; }

  get timeFormat(): string { return splitForDisplay(this.dateTimeFormat).timeFormat; }
  get dateFormat(): string { return splitForDisplay(this.dateTimeFormat).dateFormat; }
  get formattedTime(): string { return formatDateTime(this.currentTime, this.timeFormat, this.timezone); }
  get formattedDate(): string { return formatDateTime(this.currentTime, this.dateFormat, this.timezone); }
  get timezoneAbbr(): string | null { return getTimezoneAbbr(this.currentTime, this.timezone); }

  /** Merged labels — defaults overridden by whatever the consumer provides. */
  get l(): Required<TimelineLabels> { return { ...DEFAULT_LABELS, ...this.labels }; }

  resolveRewindActive(multiplier: number): string { return resolveLabel(this.l.rewindActiveTooltip, multiplier); }
  resolveFastForwardActive(multiplier: number): string { return resolveLabel(this.l.fastForwardActiveTooltip, multiplier); }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['multiplier']) {
      this.speedInputValue = String(Math.abs(this.multiplier));
      if (this.multiplier === 1) this.closeSpeedOverlay();
    }
    if (changes['live'] && this.live) this.closeSpeedOverlay();
  }

  toggleSpeedOverlay(): void {
    if (this.speedOverlayOpen) {
      this.closeSpeedOverlay();
      return;
    }
    this.speedOverlayOpen = true;
    this.updateSpeedOverlayPosition();
    this.overlayResizeListener = () => this.updateSpeedOverlayPosition();
    this.overlayScrollListener = () => this.updateSpeedOverlayPosition();
    window.addEventListener('resize', this.overlayResizeListener);
    window.addEventListener('scroll', this.overlayScrollListener, true);
  }

  closeSpeedOverlay(): void {
    this.speedOverlayOpen = false;
    this.speedOverlayPos = null;
    if (this.overlayResizeListener) window.removeEventListener('resize', this.overlayResizeListener);
    if (this.overlayScrollListener) window.removeEventListener('scroll', this.overlayScrollListener, true);
    this.overlayResizeListener = undefined;
    this.overlayScrollListener = undefined;
  }

  private updateSpeedOverlayPosition(): void {
    const badge = this.elRef.nativeElement.querySelector('[data-speed-badge]');
    if (!badge) return;
    const rect = badge.getBoundingClientRect();
    this.speedOverlayPos = this.liveButtonPosition === 'right'
      ? { bottom: window.innerHeight - rect.top + 6, right: window.innerWidth - rect.right }
      : { bottom: window.innerHeight - rect.top + 6, left: rect.left };
    this.cdr.markForCheck();
  }

  onSliderChange(e: Event): void {
    this.setSpeed.emit(Number((e.target as HTMLInputElement).value));
  }

  onSpeedInputChange(e: Event): void {
    this.speedInputValue = (e.target as HTMLInputElement).value;
  }

  commitSpeedInput(): void {
    const parsed = Math.round(Number(this.speedInputValue));
    if (Number.isFinite(parsed)) this.setSpeed.emit(parsed);
    else this.speedInputValue = String(this.absMultiplier);
  }

  @HostListener('document:pointerdown', ['$event'])
  onDocumentPointerDown(e: PointerEvent): void {
    if (!this.speedOverlayOpen) return;
    const target = e.target as HTMLElement;
    if (target.closest('[data-speed-overlay]') || target.closest('[data-speed-badge]')) return;
    this.speedOverlayOpen = false;
    this.cdr.markForCheck();
  }

  @HostListener('document:keydown.escape')
  onDocumentEscape(): void {
    if (!this.speedOverlayOpen) return;
    this.speedOverlayOpen = false;
    this.cdr.markForCheck();
  }

  ngAfterViewInit(): void {
    const el = this.containerRef?.nativeElement;
    if (!el) return;
    this.ro = new ResizeObserver(([entry]) => {
      this.isNarrow = entry.contentRect.width < 520;
    });
    this.ro.observe(el);
  }

  ngOnDestroy(): void {
    this.ro?.disconnect();
    if (this.overlayResizeListener) window.removeEventListener('resize', this.overlayResizeListener);
    if (this.overlayScrollListener) window.removeEventListener('scroll', this.overlayScrollListener, true);
  }
}

// packages/react/src/components/TimelineControls.tsx
import React, { useRef, useState, useEffect, useLayoutEffect, useMemo } from 'react';
import * as Cesium from 'cesium';
import {
  type TimelineTheme,
  type TimelineLabels,
  DEFAULT_LABELS,
  resolveLabel,
  formatDateTime,
  getTimezoneAbbr,
  splitForDisplay,
} from '@kteneyck/cesium-timeline-core';

/** React-specific controls props (uses Cesium.JulianDate for currentTime). */
export interface ControlsProps {
  currentTime: Cesium.JulianDate;
  isPlaying: boolean;
  multiplier: number;
  dateTimeFormat?: string;
  onDateTimeClick?: () => void;
  /** @see TimelineBaseProps.timezone */
  timezone?: string;
  onPlayPause: (isPlaying: boolean) => void;
  onJumpToStart: () => void;
  onRewind: () => void;
  onFastForward: () => void;
  onJumpToEnd: () => void;
  onJumpToLive: () => void;
  onResetSpeed: () => void;
  onSetSpeed: (value: number) => void;
  /** @see TimelineBaseProps.minSpeed */
  minSpeed?: number;
  /** @see TimelineBaseProps.maxSpeed */
  maxSpeed?: number;
  isLive: boolean;
  hasStartTime: boolean;
  hasEndTime: boolean;
  showJumpToStart?: boolean;
  showJumpToEnd?: boolean;
  theme: TimelineTheme;
  swimLanesVisible?: boolean;
  onToggleSwimLanes?: () => void;
  /** Overrides for control-bar labels and tooltips (i18n / custom verbiage). */
  labels?: Partial<TimelineLabels>;
  /** @see TimelineBaseProps.liveButtonSize */
  liveButtonSize?: 'sm' | 'md' | 'lg';
  /** @see TimelineBaseProps.liveButtonPosition */
  liveButtonPosition?: 'left' | 'right';
  /** @see TimelineBaseProps.showLive */
  showLive?: boolean;
  /** @see TimelineBaseProps.live */
  live?: boolean;
}

const NARROW_BREAKPOINT = 520;

/** Two vertical bars rendered as SVG — consistent across all platforms. */
const PauseIcon = () => (
  <svg width="14" height="16" viewBox="0 0 14 16" fill="currentColor" aria-hidden="true">
    <rect x="1" y="0" width="4" height="16" rx="1" />
    <rect x="9" y="0" width="4" height="16" rx="1" />
  </svg>
);

/** Chevron pointing upward (swim lanes expanded — click to collapse). */
const ChevronDownIcon = () => (
  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <polyline points="3,5 7,9 11,5" />
  </svg>
);

/** Chevron pointing downward (swim lanes collapsed — click to expand). */
const ChevronUpIcon = () => (
  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <polyline points="3,9 7,5 11,9" />
  </svg>
);

const LIVE_SIZE_MAP = {
  sm: { width: 44, height: 18, fontSize: '10px', dot: 5, borderRadius: '3px' },
  md: { width: 56, height: 22, fontSize: '11px', dot: 6, borderRadius: '3px' },
  lg: { width: 72, height: 30, fontSize: '13px', dot: 8, borderRadius: '4px' },
} as const;

export const TimelineControls: React.FC<ControlsProps> = ({
  currentTime,
  isPlaying,
  multiplier,
  dateTimeFormat,
  timezone,
  isLive,
  hasStartTime,
  hasEndTime,
  showJumpToStart = true,
  showJumpToEnd = true,
  onPlayPause,
  onJumpToStart,
  onRewind,
  onFastForward,
  onJumpToEnd,
  onJumpToLive,
  onResetSpeed,
  onSetSpeed,
  minSpeed = 1,
  maxSpeed = 100,
  onDateTimeClick,
  theme,
  swimLanesVisible,
  onToggleSwimLanes,
  labels: labelOverrides,
  liveButtonSize = 'md',
  liveButtonPosition = 'left',
  showLive = true,
  live = false,
}) => {
  const isRewinding    = multiplier < 0;
  const isFastForward  = multiplier > 1;
  const isNormalSpeed  = multiplier === 1;
  const absMultiplier  = Math.abs(multiplier);

  const L = useMemo(
    () => ({ ...DEFAULT_LABELS, ...labelOverrides }),
    [labelOverrides],
  );

  const containerRef = useRef<HTMLDivElement>(null);
  const [isNarrow, setIsNarrow] = useState(false);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const ro = new ResizeObserver(([entry]) => {
      setIsNarrow(entry.contentRect.width < NARROW_BREAKPOINT);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // ── Playback-speed overlay (slider + input, opened from the speed badge) ──
  const [speedOverlayOpen, setSpeedOverlayOpen] = useState(false);
  const [speedInputValue, setSpeedInputValue] = useState(() => String(Math.abs(multiplier)));
  const speedBadgeRef = useRef<HTMLButtonElement>(null);
  const speedOverlayRef = useRef<HTMLDivElement>(null);

  // Fixed-position coordinates (viewport-relative) so the overlay escapes any
  // ancestor's `overflow: hidden` and stacks above other page content (e.g. a
  // Cesium globe elsewhere on the page). Recomputed on open/resize/scroll.
  const [speedOverlayPos, setSpeedOverlayPos] = useState<{ bottom: number; left?: number; right?: number } | null>(null);

  useEffect(() => {
    setSpeedInputValue(String(Math.abs(multiplier)));
  }, [multiplier]);

  useEffect(() => {
    if (multiplier === 1 || live) setSpeedOverlayOpen(false);
  }, [multiplier, live]);

  useLayoutEffect(() => {
    if (!speedOverlayOpen) { setSpeedOverlayPos(null); return; }
    const updatePosition = () => {
      const badge = speedBadgeRef.current;
      if (!badge) return;
      const rect = badge.getBoundingClientRect();
      setSpeedOverlayPos(
        liveButtonPosition === 'right'
          ? { bottom: window.innerHeight - rect.top + 6, right: window.innerWidth - rect.right }
          : { bottom: window.innerHeight - rect.top + 6, left: rect.left }
      );
    };
    updatePosition();
    window.addEventListener('resize', updatePosition);
    window.addEventListener('scroll', updatePosition, true);
    return () => {
      window.removeEventListener('resize', updatePosition);
      window.removeEventListener('scroll', updatePosition, true);
    };
  }, [speedOverlayOpen, liveButtonPosition]);

  useEffect(() => {
    if (!speedOverlayOpen) return;
    const handlePointerDown = (e: PointerEvent) => {
      const target = e.target as Node;
      if (speedOverlayRef.current?.contains(target)) return;
      if (speedBadgeRef.current?.contains(target)) return;
      setSpeedOverlayOpen(false);
    };
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setSpeedOverlayOpen(false);
    };
    document.addEventListener('pointerdown', handlePointerDown);
    document.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('pointerdown', handlePointerDown);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [speedOverlayOpen]);

  const commitSpeedInput = () => {
    const parsed = Math.round(Number(speedInputValue));
    if (Number.isFinite(parsed)) {
      onSetSpeed(parsed);
      setSpeedInputValue(String(parsed));
    } else {
      setSpeedInputValue(String(Math.abs(multiplier)));
    }
  };

  const baseBtn: React.CSSProperties = {
    background: 'none',
    border: '1px solid transparent',
    cursor: 'pointer',
    fontSize: '16px',
    padding: '0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '32px',
    width: '32px',
    height: '32px',
    borderRadius: '4px',
    transition: 'background-color 0.15s, color 0.15s',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    flexShrink: 0,
    lineHeight: 1,
  };

  const btn  = (active: boolean): React.CSSProperties => ({
    ...baseBtn,
    color:  active ? theme.buttonActiveColor : theme.buttonColor,
    borderColor: active ? `${theme.buttonActiveColor}33` : 'transparent',
  });

  const onEnter = (e: React.MouseEvent<HTMLButtonElement>, active: boolean) => {
    e.currentTarget.style.backgroundColor = active
      ? `${theme.buttonActiveColor}22`
      : theme.buttonHoverColor + '44';
  };
  const onLeave = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.currentTarget.style.backgroundColor = 'transparent';
  };

  const liveSize = LIVE_SIZE_MAP[liveButtonSize];

  const LiveButton = !showLive ? null : (
    <button
      onClick={live ? undefined : onJumpToLive}
      style={{
        ...baseBtn,
        fontSize: liveSize.fontSize,
        fontWeight: 'bold',
        letterSpacing: '0.05em',
        width: `${liveSize.width}px`,
        minWidth: `${liveSize.width}px`,
        height: `${liveSize.height}px`,
        borderRadius: liveSize.borderRadius,
        color:   live || isLive ? theme.controlBarBackground : theme.buttonActiveColor,
        backgroundColor: live || isLive ? theme.buttonActiveColor : 'transparent',
        borderColor: theme.buttonActiveColor,
        opacity: 1,
        gap: '4px',
        cursor: live ? 'default' : 'pointer',
      }}
      onMouseEnter={live ? undefined : (e => { e.currentTarget.style.opacity = '1'; })}
      onMouseLeave={live ? undefined : (e => { e.currentTarget.style.opacity = isLive ? '1' : '0.55'; })}
      title={live ? L.liveActiveTooltip : (isLive ? L.liveActiveTooltip : L.liveTooltip)}
    >
      {(live || isLive) && (
        <span style={{
          width: `${liveSize.dot}px`,
          height: `${liveSize.dot}px`,
          borderRadius: '50%',
          backgroundColor: theme.liveDotColor,
          display: 'inline-block',
          flexShrink: 0,
        }} />
      )}
      {live || isLive ? L.liveActiveLabel : L.liveLabel}
    </button>
  );

  /** Speed badge — shown independently of the LIVE button; hidden in live mode. */
  const SpeedBadge = (!isNormalSpeed && !live) ? (
    <button
      ref={speedBadgeRef}
      onClick={() => setSpeedOverlayOpen(o => !o)}
      style={{
        ...baseBtn,
        fontSize: '11px',
        color: theme.buttonActiveColor,
        borderColor: `${theme.buttonActiveColor}44`,
        width: 'auto',
        minWidth: `${liveSize.width}px`,
        height: `${liveSize.height}px`,
        paddingLeft: '8px',
        paddingRight: '8px',
      }}
      onMouseEnter={e => onEnter(e, true)}
      onMouseLeave={onLeave}
      title={L.resetSpeedTooltip}
    >
      {isRewinding ? `◀ ${absMultiplier}×` : `${absMultiplier}× ▶`}
    </button>
  ) : null;

  const SpeedOverlay = (speedOverlayOpen && SpeedBadge && speedOverlayPos) ? (
    <div
      ref={speedOverlayRef}
      style={{
        position: 'fixed',
        ...speedOverlayPos,
        zIndex: 2147483647,
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        padding: '10px 12px',
        borderRadius: '6px',
        backgroundColor: theme.controlBarBackground,
        border: `1px solid ${theme.controlBarBorder}`,
        boxShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
        minWidth: '170px',
        fontFamily: 'system-ui, -apple-system, sans-serif',
      }}
    >
      <style>{`
        .ct-speed-input::-webkit-outer-spin-button,
        .ct-speed-input::-webkit-inner-spin-button {
          -webkit-appearance: none;
          margin: 0;
        }
        .ct-speed-input {
          -moz-appearance: textfield;
        }
      `}</style>
      <div style={{ fontSize: '11px', fontWeight: 'bold', letterSpacing: '0.03em', color: theme.labelColor }}>
        {L.speedOverlayTitle}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
        <input
          type="range"
          min={minSpeed}
          max={maxSpeed}
          step={1}
          value={absMultiplier}
          onChange={e => onSetSpeed(Number(e.target.value))}
          aria-label={L.speedInputLabel}
          style={{ flex: 1, accentColor: theme.buttonActiveColor }}
        />
        <input
          type="number"
          className="ct-speed-input"
          value={speedInputValue}
          onChange={e => setSpeedInputValue(e.target.value)}
          onBlur={commitSpeedInput}
          onKeyDown={e => {
            if (e.key === 'Enter') { commitSpeedInput(); (e.target as HTMLInputElement).blur(); }
          }}
          aria-label={L.speedInputLabel}
          style={{
            width: '48px',
            fontSize: '12px',
            padding: '2px 4px',
            borderRadius: '4px',
            border: `1px solid ${theme.controlBarBorder}`,
            backgroundColor: 'transparent',
            color: theme.labelColor,
            fontFamily: 'inherit',
          }}
        />
      </div>
      <button
        onClick={() => { onResetSpeed(); setSpeedOverlayOpen(false); }}
        title={L.resetSpeedTitle}
        style={{
          ...baseBtn,
          alignSelf: 'flex-start',
          width: 'auto',
          height: `${liveSize.height}px`,
          paddingLeft: '10px',
          paddingRight: '10px',
          fontSize: '11px',
          color: theme.buttonActiveColor,
          borderColor: `${theme.buttonActiveColor}44`,
        }}
        onMouseEnter={e => onEnter(e, true)}
        onMouseLeave={onLeave}
      >
        {L.resetSpeedLabel}
      </button>
    </div>
  ) : null;

  const LiveAndSpeedGroup = (LiveButton || SpeedBadge) && (
    <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
      {LiveButton}
      {SpeedBadge}
      {SpeedOverlay}
    </div>
  );

  return (
    <div
      ref={containerRef}
      style={{
        display: isNarrow ? 'flex' : 'grid',
        gridTemplateColumns: isNarrow ? undefined : '1fr auto 1fr',
        alignItems: 'center',
        padding: '6px 16px',
        backgroundColor: theme.controlBarBackground,
        borderBottom: `1px solid ${theme.controlBarBorder}`,
        fontFamily: 'system-ui, -apple-system, sans-serif',
      }}
    >
      {/* ── Left: Datetime + (LIVE if position=left) ── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>
        <div
          onClick={live ? undefined : onDateTimeClick}
          title={(!live && onDateTimeClick) ? L.dateTimeClickTooltip : undefined}
          style={{
            color: theme.labelColor,
            fontFamily: 'monospace',
            lineHeight: 1.15,
            cursor: (!live && onDateTimeClick) ? 'pointer' : 'default',
            borderRadius: '4px',
            padding: '2px 4px',
            transition: 'background 0.15s',
          }}
          onMouseEnter={e => { if (!live && onDateTimeClick) e.currentTarget.style.background = theme.buttonHoverColor + '44'; }}
          onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
        >
          {(() => {
            const { timeFormat, dateFormat } = splitForDisplay(dateTimeFormat);
            const tzAbbr = getTimezoneAbbr(currentTime, timezone);
            return (
              <>
                {timeFormat && (
                  <div style={{ fontSize: '2em', fontWeight: 'bold', letterSpacing: '0.02em' }}>
                    {formatDateTime(currentTime, timeFormat, timezone)}
                  </div>
                )}
                {dateFormat && (
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span style={{ fontSize: '1.15em', letterSpacing: '0.03em', color: theme.buttonActiveColor }}>
                      {formatDateTime(currentTime, dateFormat, timezone)}
                    </span>
                    {tzAbbr && (
                      <span style={{
                        fontSize: '0.9em',
                        color: theme.labelColor,
                        opacity: 0.7,
                        fontWeight: 'bold',
                        letterSpacing: '0.04em',
                      }}>
                        {tzAbbr}
                      </span>
                    )}
                  </div>
                )}
              </>
            );
          })()}
        </div>

        {liveButtonPosition === 'left' && LiveAndSpeedGroup}
      </div>

      {/* ── Center: Transport buttons ── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '2px', ...(isNarrow ? { flex: 1, justifyContent: 'center' } : {}) }}>

        {!live && showJumpToStart && (
          <button
            onClick={hasStartTime ? onJumpToStart : undefined}
            disabled={!hasStartTime}
            style={{ ...btn(false), opacity: hasStartTime ? 1 : 0.3, cursor: hasStartTime ? 'pointer' : 'default' }}
            onMouseEnter={hasStartTime ? e => onEnter(e, false) : undefined}
            onMouseLeave={hasStartTime ? onLeave : undefined}
            title={hasStartTime ? L.jumpToStartTooltip : L.noStartTimeTooltip}
          >⏮</button>
        )}

        {!live && (
          <button
            onClick={onRewind}
            style={btn(isRewinding)}
            onMouseEnter={e => onEnter(e, isRewinding)}
            onMouseLeave={onLeave}
            title={isRewinding ? resolveLabel(L.rewindActiveTooltip, absMultiplier) : L.rewindTooltip}
          >◀◀</button>
        )}

        {!live && (
          <button
            onClick={() => onPlayPause(!isPlaying)}
            style={{
              ...baseBtn,
              color: theme.buttonActiveColor,
              fontSize: '18px',
              width: '40px',
              minWidth: '40px',
              height: '40px',
              borderColor: `${theme.buttonActiveColor}55`,
              borderRadius: '50%',
              paddingLeft: isPlaying ? '0' : '2px',
            }}
            onMouseEnter={e => onEnter(e, true)}
            onMouseLeave={onLeave}
            title={isPlaying ? L.pauseTooltip : (isRewinding ? L.playFromRewindTooltip : L.playTooltip)}
          >
            {isPlaying ? <PauseIcon /> : '▶'}
          </button>
        )}

        {!live && (
          <button
            onClick={onFastForward}
            style={{ ...btn(isFastForward), width: 'auto', paddingLeft: '6px', paddingRight: '6px' }}
            onMouseEnter={e => onEnter(e, isFastForward)}
            onMouseLeave={onLeave}
            title={isFastForward ? resolveLabel(L.fastForwardActiveTooltip, absMultiplier) : L.fastForwardTooltip}
          >▶▶</button>
        )}

        {!live && showJumpToEnd && (
          <button
            onClick={hasEndTime ? onJumpToEnd : undefined}
            disabled={!hasEndTime}
            style={{ ...btn(false), opacity: hasEndTime ? 1 : 0.3, cursor: hasEndTime ? 'pointer' : 'default' }}
            onMouseEnter={hasEndTime ? e => onEnter(e, false) : undefined}
            onMouseLeave={hasEndTime ? onLeave : undefined}
            title={hasEndTime ? L.jumpToEndTooltip : L.noEndTimeTooltip}
          >⏭</button>
        )}

      </div>

      {/* ── Right: LIVE (if position=right) + swim-lane toggle (or spacer) ── */}
      {!isNarrow && (
        <div style={{ display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: '8px' }}>
          {liveButtonPosition === 'right' && LiveAndSpeedGroup}
          {onToggleSwimLanes != null && swimLanesVisible != null && (
            <button
              onClick={onToggleSwimLanes}
              style={{
                ...baseBtn,
                color: theme.buttonActiveColor,
                borderColor: `${theme.buttonActiveColor}33`,
              }}
              onMouseEnter={e => onEnter(e, swimLanesVisible)}
              onMouseLeave={onLeave}
              title={swimLanesVisible ? L.collapseSwimLanesTooltip : L.expandSwimLanesTooltip}
            >
              {swimLanesVisible ? <ChevronDownIcon /> : <ChevronUpIcon />}
            </button>
          )}
        </div>
      )}

      {isNarrow && onToggleSwimLanes != null && swimLanesVisible != null && (
        <button
          onClick={onToggleSwimLanes}
          style={{
            ...baseBtn,
            color: theme.buttonActiveColor,
            borderColor: `${theme.buttonActiveColor}33`,
            marginLeft: '4px',
          }}
          onMouseEnter={e => onEnter(e, swimLanesVisible)}
          onMouseLeave={onLeave}
          title={swimLanesVisible ? L.collapseSwimLanesTooltip : L.expandSwimLanesTooltip}
        >
          {swimLanesVisible ? <ChevronDownIcon /> : <ChevronUpIcon />}
        </button>
      )}
    </div>
  );
};
